### PR TITLE
Refactor the example for better testing

### PR DESCRIPTION
**Pull request by yan-qi**

### CODE REVIEW

**Comment by yan-qi** [comment]
Hi Tao, 

Can you help me have a review on this commit?

Thanks,
Yan

**Comment by hzhang22** [comment]
Since most of the codes are auto-generated. I mainly read "ReadWriteTest" and "GenerateTestData". These two classes look good to me.

**Comment by crazymooner** [comment]
Looks good. I will change my test accordingly.

**Comment by yan-qi** [comment]
Thanks, :)

**Pull request merged**
